---
- name: Create stack root directory
  file:
    path: "{{ matter_server_container_stack_location }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create Matter Server directories
  file:
    path: "{{ matter_config_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy Docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ matter_server_container_stack_location }}/docker-compose.yml"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Start Docker containers using docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ matter_server_container_stack_location }}"
  tags: start-stacks

- name: Adding the Systemd units for docker-compose management
  import_role:
    name: docker-compose-systemd
  vars:
    docker_compose_dir_path: "{{ matter_server_container_stack_location }}"
    stack_name: container-stack-matter

- name: Stop Docker containers if running
  block:
    - name: Check whether the docker file exist
      stat:
        path: "{{ matter_server_container_stack_location }}/docker-compose.yml"
      register: matter_server_container_stack_location_docker_compose_file

    - name: Check validity of compose file
      shell: "docker compose -f {{ matter_server_container_stack_location }}/docker-compose.yml config"
      register: ha_server_container_stack_docker_compose_file_validate
      ignore_errors: yes

    - name: Stopping using docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ matter_server_container_stack_location }}"
        state: absent
      when: matter_server_container_stack_location_docker_compose_file.stat.exists and ha_server_container_stack_docker_compose_file_validate.failed|bool != true
  tags: [ 'never', 'stop-stacks' ]