---
# GLOBAL
gv_server_timezone: Europe/Amsterdam

# USER
ansible_user: ubuntu
gv_local_ha_user: ha-user
gv_local_ha_uid: 1005
gv_local_ha_group: home-automation-server-users
gv_local_ha_gid: 1005
gv_local_ha_user_home: "/home/{{ gv_local_ha_user }}"

gv_docker_network_name: ha-server-network

# Storage location type. Options : [local, nfs]
gv_storage_location_type: local

## LOCAL
gv_server_data_root_local_mount_path: /mnt/server_data

## NFS - uncomment and configure following for NFS

#gv_nfs_server_address: <nfs-address>
#gv_server_data_root_local_mount_path: /mnt/server_data
#gv_server_data_remote_path: /mnt/your-remote-mount-path

# COMMON
gv_container_data_dir_name: container_data
gv_container_data_root: "{{ gv_server_data_root_local_mount_path }}/{{ gv_container_data_dir_name | default('container_data') }}"




