---
- name: Create stack root directory
  file:
    path: "{{ ha_server_container_stack_location }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create Home Assistant directories
  file:
    path: "{{ homeassistant_config_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create ESP Home directories
  file:
    path: "{{ esphome_config_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create ESP Home cache dir
  file:
    path: "{{ ha_server_container_stack_location }}/esphome/cache"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create Scrypted directories
  file:
    path: "{{ scrypted_config_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Avahi Daemon for Scrypted
  apt:
    name: avahi-daemon
    update_cache: yes

- name: Copy Docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ ha_server_container_stack_location }}/docker-compose.yml"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Start Docker containers using docker-compose
  community.docker.docker_compose:
    project_src: "{{ ha_server_container_stack_location }}"
  tags: start-stacks

- name: Adding the Systemd units for docker-compose management
  import_role:
    name: docker-compose-systemd
  vars:
    docker_compose_dir_path: "{{ ha_server_container_stack_location }}"
    stack_name: container-stack-home-automation

- name: Stop Docker containers if running
  block:
    - name: Check wether the docker file exist
      stat:
        path: "{{ ha_server_container_stack_location }}/docker-compose.yml"
      register: ha_server_container_stack_location_docker_compose_file

    - name: Check validity of compose file
      shell: "docker-compose -f {{ ha_server_container_stack_location }}/docker-compose.yml config"
      register: ha_server_container_stack_docker_compose_file_validate
      ignore_errors: yes

    - name: Stopping using docker compose
      community.docker.docker_compose:
        project_src: "{{ ha_server_container_stack_location }}"
        state: absent
      when: ha_server_container_stack_location_docker_compose_file.stat.exists and ha_server_container_stack_docker_compose_file_validate.failed|bool != true
  tags: [ 'never', 'stop-stacks' ]